eNear Bridge
aurora-is-near/near-erc20-connector pull request #1
Opened 2021-03-10 08:55 UTC by vince0656

2021-03-31 12:57 UTC, djsatok requested changes

2021-03-31 12:57 UTC, djsatok commented on eNear/contracts/AdminControlled.sol
> +// SPDX-License-Identifier: MIT
Let's remove this file and use the AdminControlled from the Rainbow Bridge Repo as dependency:
https://github.com/near/rainbow-bridge/blob/master/contracts/eth/nearbridge/contracts/AdminControlled.sol

2021-03-31 12:57 UTC, djsatok commented on eNear/contracts/eNear.sol
> +    function init(
Shouldn't be this method admin controlled?
Where is the proxy code?

2021-03-31 12:57 UTC, djsatok commented on eNear/contracts/eNear.sol
> +    event NearToEthTransferFinalised (
Should we add in this event the NEAR sender for uniformity fo the events?

2021-03-31 12:57 UTC, djsatok commented on eNear/contracts/eNear.sol
> +        bytes memory _nearTokenFactory,
Let's rename `_nearTokenFactory` into `nearConnector`

2021-03-31 12:57 UTC, djsatok commented on eNear/contracts/Bridge.sol
> +        require(prover_.proveOutcome(proofData, proofBlockHeight), "Proof should be valid");
Please add here the `minBlockAcceptanceHeight` check. See more in the recent version of the token-connector:
https://github.com/near/rainbow-token-connector/blob/master/erc20-connector/contracts/Locker.sol#L36

2021-03-31 12:57 UTC, djsatok commented on nearBridge/Cargo.toml
> +admin-controlled = { git = "https://github.com/near/rainbow-bridge", rev = "3a60b7eac2f06d160bd7b20b67a181961c08055d" }
Need to update all the links to the most recent revisions

2021-03-31 12:57 UTC, djsatok commented on eNear/contracts/eNear.sol
> +    uint constant PAUSED_XFER_TO_NEAR = 1 << 1;
`PAUSED_XFER_TO_NEAR` -> `PAUSE_TRANSFER_TO_NEAR`

2021-03-31 12:57 UTC, djsatok commented on eNear/contracts/eNear.sol
> +    uint constant PAUSED_FINALISE_FROM_NEAR = 1 << 0;
`PAUSED_FINALISE_FROM_NEAR` -> `PAUSE_FINALISE_FROM_NEAR`

2021-04-03 17:45 UTC, vince0656 commented on eNear/contracts/Bridge.sol
> +        require(prover_.proveOutcome(proofData, proofBlockHeight), "Proof should be valid");
ok I have added back in but thought we removed it because we can upgrade the contract through the proxy set up

2021-04-03 18:44 UTC, vince0656 commented on eNear/contracts/eNear.sol
> +    function init(
```
Shouldn't be this method admin controlled?
Where is the proxy code?
```

```
Let's remove this file and use the AdminControlled from the Rainbow Bridge Repo as dependency:
https://github.com/near/rainbow-bridge/blob/master/contracts/eth/nearbridge/contracts/AdminControlled.sol
```

In response to the above two comments, when it comes to proxies on ETH, the deployment of logic and data initialisation has to be separate i.e. no constructor. 

The reason I have a local copy of `AdminControlled` is because if you inherit the contract as a dependency, you have to call its constructor when deploying eNear. However, this would not set the state in the proxy. Therefore, by making a local copy, I have taken out the constructor and have instead added the logic to the `init` method. 

The proxy contract I have been using is the OZ `TransparentUpgradeableProxy` out the box with no changes and therefore it is not in the repo

2021-04-03 19:24 UTC, vince0656 commented on nearBridge/Cargo.toml
> +admin-controlled = { git = "https://github.com/near/rainbow-bridge", rev = "3a60b7eac2f06d160bd7b20b67a181961c08055d" }
used published crates where possible and where not possible, bumped up the versions

2021-04-19 03:25 UTC, paouvrard commented on eNear/test/eNear.test.js
> +  'Unlock': {
Should this be the `'Lock'` event (returned result) from locking $NEAR on NEAR ?

2021-04-19 03:29 UTC, paouvrard commented on nearBridge/src/lib.rs
> +    }
Should this function return the Lock data similar to this https://github.com/near/rainbow-token-connector/blob/7fb86958362fe8e4455ebbcdb00caac067eda2ff/bridge-token-factory/src/lib.rs#L231 for creating the Lock proof ?

2021-04-21 21:28 UTC, mfornet commented on nearBridge/src/lib.rs
> +        contract.migrate_to_ethereum(alice_eth_address())
```suggestion
        contract.migrate_to_ethereum(alice_eth_address());
```

We should not return nothing in the end for this test. **This applies to other tests as well**

2021-04-21 21:28 UTC, mfornet commented on nearBridge/Cargo.toml
> +admin-controlled = { git = "https://github.com/near/rainbow-bridge", rev = "3a5373168e720d237ab451e8d41e81010693f876" }
This is unfortunate, definitely something we need to fix in our end with a proper release process. I'll update this once we fixed it. (Not blocking for merge, just a note)

2021-04-21 21:28 UTC, mfornet commented on eNear/contracts/Bridge.sol
> +    // OutcomeReciptId -> Used
```suggestion
    // OutcomeRecieptId -> Used
```

2021-04-21 21:28 UTC, mfornet commented on eNear/contracts/Bridge.sol
> +pragma solidity 0.6.12;
Consider moving to 0.8. (Not blocking this PR, just a note)

2021-04-21 21:28 UTC, mfornet commented on eNear/package.json
> +    "rainbow-bridge-lib": "https://github.com/near/rainbow-bridge-lib",
This is an archived repository. Let's remove this dependency and use utils from rainbow-bridge

2021-04-21 21:28 UTC, mfornet commented on eNear/package.json
> +    "rainbow-bridge": "https://github.com/near/rainbow-bridge#4826f4573a9039e0ee2f43ba964f709989c0906f",
There were some noticeable optimisation the solidity implementation of Borsh. To enable update commit hash to: https://github.com/aurora-is-near/rainbow-bridge/commit/4016930da95b8fdf7a462ed454ad32257b1b7b5c

2021-04-21 21:28 UTC, mfornet commented on eNear/contracts/eNear.sol
> +        uint256 _pausedFlags
Add docstring with description for parameters.

2021-04-22 08:13 UTC, vince0656 commented on nearBridge/src/lib.rs
> +            env::panic(b"Method is either paused or ETH address is invalid");
Ok I have wrapped this in an if to check attached deposit

2021-04-22 08:20 UTC, vince0656 commented on nearBridge/Cargo.toml
> +admin-controlled = { git = "https://github.com/near/rainbow-bridge", rev = "3a5373168e720d237ab451e8d41e81010693f876" }
👍

2021-04-22 20:11 UTC, vince0656 commented on eNear/package.json
> +    "rainbow-bridge-lib": "https://github.com/near/rainbow-bridge-lib",
Do you have an example of using the utils. Thanks

2021-04-22 20:22 UTC, vince0656 commented on eNear/package.json
> +    "rainbow-bridge": "https://github.com/near/rainbow-bridge#4826f4573a9039e0ee2f43ba964f709989c0906f",
I seem to be getting the following issue when upgrading this dependency: `Error HH306: Missing task argument file`. I find it really strange. I just so happened to upgrade to 0.8.3 at the same time and thought it was the solidity version causing the problem but looks like it's something else

2021-04-22 21:31 UTC, abacabadabacaba requested changes

2021-04-22 21:31 UTC, abacabadabacaba commented on nearBridge/src/lib.rs
> +        if self.is_paused(PAUSE_MIGRATE_TO_ETH) || is_valid_eth_address(eth_recipient_clone) == false {
Never compare a boolean value with a constant.

2021-04-22 21:31 UTC, abacabadabacaba commented on nearBridge/src/lib.rs
> +            }
These actions will be rolled back due to panic.

2021-04-23 08:26 UTC, djsatok commented on eNear/contracts/eNear.sol
> +        emit NearToEthTransferFinalised(_msgSender(), result.amount, result.recipient);
@abacabadabacaba , isn't it for support of meta-tx?

2021-04-24 09:51 UTC, vince0656 commented on eNear/contracts/Bridge.sol
> +    mapping(bytes32 => bool) public usedProofs_;
https://github.com/aurora-is-near/rainbow-token-connector/blob/master/erc20-connector/contracts/Locker.sol

2021-04-24 09:51 UTC, vince0656 commented on eNear/contracts/Bridge.sol
> +    mapping(bytes32 => bool) public usedProofs_;
Not sure to be honest - `Bridge.sol` is based on `Locker.sol` linked above

2021-04-24 09:55 UTC, vince0656 commented on eNear/hardhat.config.js
> +}
I have a github action on this repo which runs the tests on push and pull. In the github env, private key is not defined and this causes a problem when trying to run the tests

2021-04-24 10:09 UTC, vince0656 commented on nearBridge/src/lib.rs
> +        if self.is_paused(PAUSE_MIGRATE_TO_ETH) || is_valid_eth_address(eth_recipient_clone) == false {
can you expand please?

2021-04-24 10:09 UTC, vince0656 commented on nearBridge/src/lib.rs
> +            }
oh I thought all actions in a transaction were final until the panic @djsatok

2021-04-27 20:10 UTC, vince0656 commented on nearBridge/src/lib.rs
> +            }
fixed

2021-04-27 20:11 UTC, vince0656 commented on nearBridge/src/lib.rs
> +        if self.is_paused(PAUSE_MIGRATE_TO_ETH) || is_valid_eth_address(eth_recipient_clone) == false {
fixed

2021-04-27 20:11 UTC, vince0656 commented on nearBridge/Cargo.toml
> +serde_json = "*"
fixed

2021-04-27 20:11 UTC, vince0656 commented on nearBridge/.gitignore
> +*.iml
fixed

2021-04-27 20:11 UTC, vince0656 commented on eNear/hardhat.config.js
> +    }
fixed

2021-04-27 20:12 UTC, vince0656 commented on .gitignore
> +.DS_Store
fixed

2021-04-28 07:59 UTC, vince0656 commented on nearBridge/src/lib.rs
> +        contract.migrate_to_ethereum(alice_eth_address())
Done - thanks!

2021-05-03 16:39 UTC, vince0656 commented on eNear/scripts/1_deploy_eNear.js
> +  const pausedFlagValues = prompt('Paused flag values? ');
fixed

2021-05-03 16:39 UTC, vince0656 commented on eNear/scripts/2_pause_e_near_method.js
> +  const eNearProxyAddress = prompt('eNear proxy address? ')
fixed

2021-05-03 16:39 UTC, vince0656 commented on eNear/contracts/eNear.sol
> +        emit NearToEthTransferFinalised(_msgSender(), result.amount, result.recipient);
fixed

2021-05-03 16:40 UTC, vince0656 commented on eNear/test/ERC20.behavior.js
> +};
fixed

2021-05-03 16:41 UTC, vince0656 commented on nearBridge/src/lib.rs
> +/**
fixed

2021-05-03 16:41 UTC, vince0656 commented on eNear/package.json
> +}
only using dependencies we need

2021-05-18 11:12 UTC, paouvrard commented on eNear/contracts/Bridge.sol
> +    function _parseAndConsumeProof(bytes memory proofData, uint64 proofBlockHeight)
The rainbow-bridge-frontend and Aurora web app would greatly benefit from having a way to match a `finaliseNearToEthTransfer tx hash` to the proof which was used by that transaction.

This would allow determining the `finaliseNearToEthTransfer tx hash`  from the tx hash which initiated the transfer.

https://github.com/aurora-is-near/rainbow-token-connector/issues/59

On Ethereum side, we are querying the local storage directly with eth_getStorageAt to check if a proof was used, but this doesn't allow matching the proof to the transaction which finalized the transfer and recorded that proof.

Emitting an event containing the receiptId would enable this matching of proof and `finaliseNearToEthTransfer tx hash`.
Not sure about the best way to do this on NEAR side, ideally without having to use an indexing service.

cc @mfornet @djsatok

2021-05-18 12:58 UTC, vince0656 commented on eNear/contracts/Bridge.sol
> +    function _parseAndConsumeProof(bytes memory proofData, uint64 proofBlockHeight)
Interesting. I have added an event that emits the receipt ID

2021-05-18 13:08 UTC, paouvrard commented on eNear/contracts/Bridge.sol
> +    function _parseAndConsumeProof(bytes memory proofData, uint64 proofBlockHeight)
For convenience, we may also need a `view` function on `usedProofs_` as an alternative to the getStorageAt query.

2021-05-18 13:17 UTC, vince0656 commented on eNear/contracts/Bridge.sol
> +    function _parseAndConsumeProof(bytes memory proofData, uint64 proofBlockHeight)
as its public mapping you can access it but I will drop the underscore

2021-05-19 03:17 UTC, abacabadabacaba requested changes

2021-05-19 03:17 UTC, abacabadabacaba commented on eNear/test/eNear.test.js
> +      proof.outcome_proof.outcome.status.SuccessValue = serialize(SCHEMA, 'MigrateNearToEthereum', {
Here you are mutating the value returned by `require('./proof_template.json')`. This is not great, because multiple calls to `require` will return the same value, which may cause interference between tests.

2021-05-19 03:17 UTC, abacabadabacaba commented on eNear/test/eNear.test.js
> +      let proof = require('./proof_template_invalid_executor.json');
Why have a separate template with an invalid executor, instead of reusing the common template?

2021-05-19 03:17 UTC, abacabadabacaba commented on nearBridge/src/lib.rs
> +        if self.is_paused(PAUSE_MIGRATE_TO_ETH) || !is_valid_eth_address(eth_recipient_clone) {
Why not use `check_not_paused`?

2021-05-19 07:50 UTC, vince0656 commented on eNear/contracts/eNear.sol
> +        address indexed sender,
I think it was a nice to have but not essential so will remove to save GAS

2021-05-19 07:53 UTC, vince0656 commented on eNear/contracts/eNear.sol
> +    function transferToNear(uint256 _amount, string calldata _nearReceiverAccountId)
`calldata` is cheaper as memory copies the string into memory where as calldata just reads straight from the TX data. calldata is only possible with external methods

2021-05-19 07:54 UTC, vince0656 commented on eNear/package.json
> +    "test": "npx hardhat test"
my understanding is that it is not recommended to install hardhat globally hence the need for npx

2021-05-19 07:56 UTC, vince0656 commented on eNear/hardhat.config.js
> +require("@nomiclabs/hardhat-truffle5");
yes I tried to remove waffle but the hardhat tasks require it for ethers

2021-05-19 07:57 UTC, vince0656 commented on eNear/test/eNear.test.js
> +const { BN, constants, expectEvent, expectRevert } = require('@openzeppelin/test-helpers');
the eNear test file is a truffle based test file which injects web3 so I think this is fine

2021-05-19 07:58 UTC, vince0656 commented on eNear/test/eNear.test.js
> +contract('eNear bridging', function ([deployer, proxyAdmin, prover, eNearAdmin, alice, bob, ...otherAccounts]) {
good spot - I will remove

2021-05-19 07:59 UTC, vince0656 commented on nearBridge/src/lib.rs
> +        if self.is_paused(PAUSE_MIGRATE_TO_ETH) || !is_valid_eth_address(eth_recipient_clone) {
I think because the `check_not_paused` method reverts and I wanted to control the reverting myself. I want to revert within the if block

2021-05-19 08:20 UTC, vince0656 commented on eNear/test/eNear.test.js
> +      proof.outcome_proof.outcome.status.SuccessValue = serialize(SCHEMA, 'MigrateNearToEthereum', {
adjusted to use object.assign

2021-05-19 08:20 UTC, vince0656 commented on eNear/test/eNear.test.js
> +      proof.outcome_proof.outcome.status.SuccessValue = serialize(SCHEMA, 'MigrateNearToEthereum', {
but think it's not quite right as there was some interference

2021-05-19 08:20 UTC, vince0656 commented on eNear/test/eNear.test.js
> +      let proof = require('./proof_template_invalid_executor.json');
re-use common template now

2021-05-19 21:39 UTC, abacabadabacaba commented on eNear/contracts/eNear.sol
> +    function transferToNear(uint256 _amount, string calldata _nearReceiverAccountId)
The data will need to be copied into memory anyway when creating an event.

2021-05-19 21:40 UTC, abacabadabacaba commented on eNear/package.json
> +    "test": "npx hardhat test"
`yarn run` adds `node_modules/.bin` to `$PATH`, so locally installed commands work without `npx`.

2021-05-19 21:41 UTC, abacabadabacaba commented on eNear/hardhat.config.js
> +require("@nomiclabs/hardhat-truffle5");
Did you try to remove Truffle instead?

2021-05-19 21:43 UTC, abacabadabacaba commented on nearBridge/src/lib.rs
> +        if self.is_paused(PAUSE_MIGRATE_TO_ETH) || !is_valid_eth_address(eth_recipient_clone) {
I think that letting `check_not_paused` revert is better. Your code has a single revert for two unrelated error conditions, which is not great.

2021-05-19 21:45 UTC, abacabadabacaba commented on eNear/test/eNear.test.js
> +      proof.outcome_proof.outcome.status.SuccessValue = serialize(SCHEMA, 'MigrateNearToEthereum', {
Your solution doesn't work as it only performs a shallow clone.

2021-05-20 07:16 UTC, vince0656 commented on eNear/test/eNear.test.js
> +      proof.outcome_proof.outcome.status.SuccessValue = serialize(SCHEMA, 'MigrateNearToEthereum', {
ok i have fixed

2021-05-20 07:18 UTC, vince0656 commented on eNear/package.json
> +    "test": "npx hardhat test"
that's awesome - i have changed

2021-05-20 07:33 UTC, vince0656 commented on eNear/hardhat.config.js
> +require("@nomiclabs/hardhat-truffle5");
truffle is needed for the unit tests

2021-05-22 10:42 UTC, vince0656 commented
As mentioned above in one of the comment threads, I was unable to use the latest ^0.8 contracts from the `rainbow-bridge` repo and that is why I am on an older commit for the rainbow bridge dependency. I was unable to use the latest contracts because of an issue in hardhat which the hardhat team have now investigated and diagnosed:

https://github.com/aurora-is-near/rainbow-bridge/issues/588

Any insight and thoughts @abacabadabacaba would be appreciated

2021-05-22 23:54 UTC, sept-en commented
@vince0656 Yes, I encountered the same issue a couple of weeks ago. Good job on noticing the origin of the issue!
As for now, I suggest you use the same version that's used in `eth-connector`, pointing to the commit `ede62fcb3614e28e8c5406300381319fec846100` (at least as a temporary solution). This commit contains all needed `AdminControlled` functionality. But for sure lacks `Borsh` contract optimizations that were introduced in the following commits. If I remember correctly, the symlink was added right in the next commit after it.

But anyway I think it'd be great to remove the symlink in the `rainbow-bridge` to allow pointing the repo to the most up-to-date head, containing all optimizations.

2021-05-23 02:19 UTC, sept-en commented
Update: working on the fix for the `rainbow-bridge` repo. This is a little bit tricky though.

2021-06-03 16:29 UTC, merged