Add near plugins & update near-sdk
aurora-is-near/near-erc20-connector pull request #40
Opened 2023-11-06 21:01 UTC by karim-en

2023-11-07 14:00 UTC, olga24912 requested changes

2023-11-07 17:13 UTC, karim-en commented on nearBridge/src/lib.rs
>              paused: Mask::default(),
2ec9c740ab346ed5fdb1e4cf05326ebdc10400c4

2023-11-07 17:13 UTC, karim-en commented on nearBridge/Cargo.toml
> +eth-types =  { git = "https://github.com/near/rainbow-bridge", rev = "bf7cc1e81ee4a4fad3e74e2c599b0b6cf3757f4d", default-features = false}
2ec9c740ab346ed5fdb1e4cf05326ebdc10400c4

2023-11-09 08:14 UTC, olga24912 approved these changes

2023-11-09 12:58 UTC, merged